server.port=8080
spring.thymeleaf.cache=false
spring.mvc.view.prefix=classpath:/templates/
spring.mvc.view.suffix=.html

# 逻辑驱动器 -> 分区
# 故意不配置 B，用于触发“letter2Partition 中未注册”的错误
# 故意配置 G=G，但不在 partition2Hardware 中配置 G，用于触发“partition2Hardware 中未注册”的错误
driver.letter2Partition=A=A,C=C,D=D,E=E,F=F,G=G

# 分区 -> 硬件实现类（全限定类名）
driver.partition2Hardware=A=cn.jxufe.disk.hardware.impl.SsdHardwareFormatter,C=cn.jxufe.disk.hardware.impl.HddHardwareFormatter,D=cn.jxufe.disk.hardware.impl.SsdHardwareFormatter,E=cn.jxufe.disk.hardware.impl.UsbHardwareFormatter,F=cn.jxufe.disk.hardware.impl.CdrHardwareFormatter